using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;

namespace _1000_7
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("У меня нет проблем, кроме моей башки");
            Thread.Sleep(1000);
            Console.WriteLine("1000 - 7, я умер, прости");
            Thread.Sleep(1000);
            Console.WriteLine("Этот ёбаный дождь нагоняет тоски");
            Thread.Sleep(1000);
            Console.WriteLine("1000 - 7, я умер, прости");
            Thread.Sleep(1000);
            Console.WriteLine("И им всем никогда меня не победить");
            Thread.Sleep(1000);
            Console.WriteLine("1000 - 7, я уже погиб");
            Thread.Sleep(2000);
            Console.WriteLine("...");
            Thread.Sleep(2000);
            for (int i = 1000; i > -1000; i -= 7)
            {
                Console.WriteLine(i + " - 7 = " + (i - 7));
                Thread.Sleep(10);
            }
            Thread.Sleep(2000);
            Console.WriteLine("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣶⣧⡀⠀");
            Console.WriteLine("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣶⣾⣿⣿⣿⣿⣿⣿⣧⠀");
            Console.WriteLine("⠀⠀⠀⠀⠀⠀⢀⣀⣤⡴⢒⣆⣠⠤⢶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠀⠀");
            Console.WriteLine("⠀⢀⣠⠤⠒⠈⠉⠋⢠⣷⣾⣿⣿⡄⢺⣿⣿⣿⣿⣿⣿⡿⠟⠋⠁⠀⠀⠀⠀⠀");
            Console.WriteLine("⣾⣯⣴⣦⣀⠀⠀⢀⣾⣿⣿⡏⢻⣧⢈⡻⢿⡩⢗⠏⢓⣀⣀⣩⣭⣤⣄⡀⠀⠀");
            Console.WriteLine("⠹⣿⣿⣿⣿⣷⠆⣼⣿⣿⣿⡇⠘⡿⠁⠀⠘⡄⠀⠘⠉⠏⠉⠿⠁⡇⠀⠩⠂⠀");
            Console.WriteLine("⠀⢻⣿⣿⡿⠋⣰⣿⣷⣬⡹⡛⢴⠃⠀⠀⠀⣃⡀⠀⣀⠄⠐⠀⠊⠄⠀⠀⠀⠀");
            Console.WriteLine("⠀⠀⢻⣿⣷⢡⣿⣿⣿⡿⢟⣳⣵⣾⣧⣠⣿⣿⣿⣶⣦⣀⣀⣄⡀⠀⠀⠀⠀⠀");
            Console.WriteLine("⠀⣦⣬⡷⡭⢾⣛⣉⢷⣾⣿⣿⣿⣿⣿⢹⣿⣿⣿⣿⣟⣛⠋⢰⣶⣶⣶⣶⣾⠏");
            Console.WriteLine("⠀⠘⢿⣍⢡⣾⡿⣵⡿⣯⣝⡻⢿⣿⡿⣻⡿⢿⡿⣛⣽⣧⢾⣮⠻⣿⣿⣿⠏⠀");
            Console.WriteLine("⠀⠀⠈⢿⡸⡏⣾⠃⢄⡁⠙⠹⠋⠻⠛⡟⠛⡟⠻⠁⠃⣸⢤⣾⡇⠘⣿⠃⠀⠀");
            Console.WriteLine("⠀⠀⠀⠈⢳⣕⡋⣰⣄⡌⢩⠘⡒⠂⠀⠃⠀⡓⢒⠀⡅⢠⡼⢛⣵⡿⠃⠀⠀⠀");
            Console.WriteLine("⠀⠀⠀⢀⣀⠙⣿⣷⡛⢿⢿⣶⣇⣼⣄⣦⣠⣇⣼⣶⠟⣫⣶⣿⣏⠀⠒⠦⣄⠀");
            Console.WriteLine("⠀⢠⡾⠙⠤⣮⣝⢿⣿⣷⡑⢭⡻⠿⠿⠿⠟⡿⠟⠅⣾⣿⡿⣫⣿⢟⣶⡀⣈⡇");
            Console.WriteLine("⠀⠘⠷⢶⣿⣮⡻⣷⡝⢿⡿⠆⠑⣶⣿⣿⣷⣾⣿⠷⣿⠏⠾⡿⣣⡿⣫⠊⠙⠀");
            Console.WriteLine("⠀⠀⠈⠄⠟⠻⡿⢊⠀⠈⠁⠀⠀⠙⠛⠛⠛⠛⠁⠀⢈⡀⠀⠈⢛⠋⠘⠄⠀⠀");
            Console.WriteLine("⠀⠀⠀⠀⠑⢄⠑⠀⣡⡸⡗⠀⠀⠀⠀⠀⠀⠀⠀⠐⢿⣡⣤⠀⢈⠁⠀⠀⠀⠀");
            Console.WriteLine("⠀⠀⠀⠀⠀⠀⠀⠛⠾⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⠯⠋⠀⠀⠀⠀⠀⠀");
            Console.WriteLine("КАРОЧЕ ???????????????????????????????");
            Console.WriteLine("");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Console.Write("1000-7?   ");
            Thread.Sleep(10);
            Console.Write("1000-7?   ");
            Thread.Sleep(5000);
        }

    }
}